
alias(
    name = "imgui",
    actual = "@imgui",
    visibility = ["//visibility:public"],
)

alias(
    name = "example",
    actual = "@imgui//:example",
    visibility = ["//visibility:public"],
)
